services:
  jupyter-lab:
    image: jupyter/datascience-notebook:latest
    container_name: devops_jupyter_notebooks
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work/notebooks
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=2d355bda37aacf782f6231150155c884e0de542e234b89f9
    restart: unless-stopped
